kind: Service
apiVersion: v1
metadata:
  name: if-sitesearch
spec:
  selector:
    app: sis-api
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  clusterIP: 10.105.83.186
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: if-sitesearch-deployment
  labels:
    app: sis-api
spec:
  replicas: ${count}
  selector:
    matchLabels:
      app: sis-api
  template:
    metadata:
      labels:
        app: sis-api
    spec:
      containers:
      - name: if-sitesearch
        image: docker-registry.sitesearch.cloud/intrafind/if-sitesearch:1.0
      imagePullSecrets:
      - name: sitesearch-secret