#this gives pods the right to access endpoints in the cluster
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: endpoint-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-endpoints
  namespace: default
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-elasticsearch-data-node
  gcePersistentDisk:
    pdName: "elasticsearch-disk-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-elasticsearch-data-node
  gcePersistentDisk:
    pdName: "elasticsearch-disk-2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-quorum
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-elasticsearch-quorum-node
  gcePersistentDisk:
    pdName: "elasticsearch-disk-quorum"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: searchservice-pv-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-searchservice-node
  gcePersistentDisk:
    pdName: "searchservice-disk-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: searchservice-pv-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gce-searchservice-node
  gcePersistentDisk:
    pdName: "searchservice-disk-2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gce-pd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
