version: '3.3'

services:
  sitesearch:
    image: intrafind/if-sitesearch:latest
    container_name: sitesearch
    environment:
      VAULT_TOKEN:
      secure_user_name: "my-user-name"
      secure_user_password: "my-password"
    labels:
      upstream: "true"
      basic-auth-protected: 'true'
    ports:
      - 80:8001
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    volumes:
      - ~/srv/sitesearch/data:/home/app_user/data:rw
    stop_signal: SIGTERM
#    cap_add:
#      - IPC_LOCK
    entrypoint: java -jar -Xmx64m app/if-sitesearch-1.0.0.jar
