#
# Copyright 2017 IntraFind Software AG. All rights reserved.
#

#server.error.whitelabel.enabled=false # to fix Swagger issue

security:
  user:
    name: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=
    password: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=

sitesearch:
  ifinderCoreHostname: sitesearch.cloud

server:
  port: 8001
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: ${security.user.password}
#    key-password: ${security.user.password}
#    key-alias: alias

spring:
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch

