#
# Copyright 2017 Alexander Orlov <alexander.orlov@loxal.net>. All rights reserved.
#

#elasticsearch:
#  clustername: mkyong-cluster
#  host: localhost
#  port: 9300

server:
  port: 8200

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch

