version: "2.0"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0-rc2
    container_name: kibana
#    image: wordpress:4.8.2-php7.1-apache
    restart: always
#    networks:
#       - sitesearch
#    volumes:
#      - ~/srv/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
#    environment:
#      SERVER_NAME: main.sitesearch.cloud
#      ELASTICSEARCH_URL: http://main
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      KIBANA_DEFAULTAPPID: kibana.defaultAppId
#      XPACK_MONITORING_ENABLED: xpack.monitoring.enabled
#
#  mysql:
#    image: mysql:5.7
#    container_name: wordpress-mysql
#    restart: always
##    networks:
##       - sitesearch
#    volumes:
#      - ~/srv/wordpress-mysql:/var/lib/mysql
##/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 65b6f240-bf83-11e7-a6a6-0b797d0cf168
##      MYSQL_ROOT_HOST: test.sitesearch.cloud
#
#networks:
#  sitesearch:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-rc2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-rc2
    container_name: elasticsearch2
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: