version: "2.0"
services:
  ops-kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0-rc2
    container_name: ops-kibana
    restart: always
    environment:
#      SERVER_NAME: ops-elasticsearch
      ELASTICSEARCH_URL: http://ops-elasticsearch:9200
    #      KIBANA_DEFAULTAPPID: kibana.defaultAppId
    #      XPACK_MONITORING_ENABLED: xpack.monitoring.enabled
    #
#    networks:
#       - sitesearch
#    volumes:
#      - ~/srv/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - ops

  ops-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-rc2
    container_name: ops-elasticsearch
    restart: always
    environment:
      - ELASTIC_PASSWORD=65b6f240-bf83-11e7-a6a6-0b797d0cf168
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ops-elk:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#      - 9300:9300
    networks:
      - ops
  ops-elasticsearch-alt:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-rc2
    container_name: ops-elasticsearch-opt
    restart: always
    environment:
      - ELASTIC_PASSWORD=65b6f240-bf83-11e7-a6a6-0b797d0cf168
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=ops-elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ops-elk-alt:/usr/share/elasticsearch/data
    networks:
      - ops

  ops-kibana-direct:
    image: kibana:4
    container_name: ops-kibana-direct
    restart: always
    environment:
#      ELASTICSEARCH_URL: http://sitesearch-elasticsearch:9200
      - "ELASTICSEARCH_URL=http://sitesearch-elasticsearch:9200"
##      SERVER_NAME: ops-elasticsearch
#      - "ELASTICSEARCH_URL=http://sitesearch-elasticsearch:9200"
#      - cluster.name=sitesearch-ops-cluster-direct
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=sitesearch-elasticsearch"
    #      KIBANA_DEFAULTAPPID: kibana.defaultAppId
    #      XPACK_MONITORING_ENABLED: xpack.monitoring.enabled
    #
#    volumes:
#      - ~/srv/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5606:5601
    networks:
      - sitesearch

volumes:
  ops-elk:
    driver: local
  ops-elk-alt:
    driver: local

networks:
  ops:
    external:
      name: ops
  sitesearch:
    external:
      name: sitesearch