version: "2.0"

services:
        # TODO not tested!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  consul:
    image: consul:1.0.1
    container_name: consul
    restart: always
    ports:
      - 8500:8500
      - 8600:8600
      - 8300:8300
      - 8301:8301
      - 8302:8302
    networks:
      - sitesearch

  bg:    # TODO sync with container_name to make it work?
    image: intrafind/router:latest
    container_name: router
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - constraint:node=master
#      - CONSUL_URL=consul:8500
    depends_on:
      - consul
      - if-sitesearch-blue
      - if-sitesearch-green
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - sitesearch

  blue:   # TODO sync with container_name to make it work?
    image: intrafind/if-sitesearch:latest
    container_name: if-sitesearch-blue
    restart: always
    ports:
      - 4443:8001
    environment:  # TODO in case it is not working, check alternative notations here: https://docs.docker.com/compose/environment-variables/
      - SECURITY_USER_PASSWORD
      - BUILD_NUMBER
      - SCM_HASH
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET
    logging:
      driver: gelf
      options:
        gelf-address: udp://ops-logstash:12201
    networks:
      - sitesearch

  green:   # TODO sync with container_name to make it work?
    image: intrafind/if-sitesearch:latest
    container_name: if-sitesearch-green
    restart: always
    ports:
      - 3443:8001
    environment:  # TODO in case it is not working, check alternative notations here: https://docs.docker.com/compose/environment-variables/
      - SECURITY_USER_PASSWORD
      - BUILD_NUMBER
      - SCM_HASH
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET
    logging:
      driver: gelf
      options:
        gelf-address: udp://ops-logstash:12201
    networks:
      - sitesearch

volumes:
  ops-consul:
    driver: local

networks:
  sitesearch:
    external:
      name: sitesearch