version: "2.0"
services:
  ops-kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: ops-kibana
    restart: always
    environment:
#      SERVER_NAME: ops-elasticsearch
      ELASTICSEARCH_URL: http://ops-elasticsearch:9200
    #      KIBANA_DEFAULTAPPID: kibana.defaultAppId
    #      XPACK_MONITORING_ENABLED: xpack.monitoring.enabled
    #
#    networks:
#       - sitesearch
#    volumes:
#      - ~/srv/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - sitesearch

  ops-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: ops-elasticsearch
    restart: always
    environment:
#      - "ELASTIC_PASSWORD=65b6f240-bf83-11e7-a6a6-0b797d0cf168"
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ops-elk:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - sitesearch
      
  ops-elasticsearch-alt:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: ops-elasticsearch-opt
    restart: always
    environment:
#      - "ELASTIC_PASSWORD=65b6f240-bf83-11e7-a6a6-0b797d0cf168"
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=ops-elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ops-elk-alt:/usr/share/elasticsearch/data
    networks:
      - sitesearch

  ops-logstash:
    image: docker.elastic.co/logstash/logstash:6.0.0
    container_name: ops-logstash
    restart: always
#    logging:
#      driver: syslog
#      options:
#        syslog-address: "udp://$IP_LOGSTASH:5000"
#        syslog-tag: "nginx-with-syslog"
    environment:
#      - ELASTIC_PASSWORD=65b6f240-bf83-11e7-a6a6-0b797d0cf168
#      - cluster.name=sitesearch-ops-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=ops-elasticsearch"
      - "xpack.monitoring.elasticsearch.url=http://ops-elasticsearch:9200"
#    volumes:
#      - ~/srv/logstash/:/usr/share/logstash
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - sitesearch

volumes:
  ops-elk:
    driver: local
  ops-elk-alt:
    driver: local

networks:
#  ops:
#    external:
#      name: ops
  sitesearch:
    external:
      name: sitesearch